//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bank_MVC_Web_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int PaymentId { get; set; }
        public decimal Sum { get; set; }
        public System.DateTime PaymentDate { get; set; }
        public int AccountId { get; set; }
        public int PaymentTypeId { get; set; }
        public decimal Total { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual PaymentType PaymentType { get; set; }
    }
}
